### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by ben-b-ow** [rubytoolbox/rubytoolbox#1065]
Visiting https://www.ruby-toolbox.com/search?q=something I get an error message:

![Screenshot 2023-01-19 at 5 13 37 PM](https://user-images.githubusercontent.com/100246332/213353725-619e807e-005e-40c8-883e-174aa89b835c.png)

**Comment by colszowka** [comment]
Thanks for reporting @ben-b-ow, I was asleep :) Some log ran full on the search server, I fixed this and it should be up again :+1:

**Comment by ben-b-ow** [comment]
Thanks!
