### ISSUE TITLE
Add a health check category to the catalog

### ISSUE THREAD

**Issue by andrepiske** [rubytoolbox/rubytoolbox#1090]
Hey all!

I'd like to suggest adding a "health check" category to the catalog. I volunteer to open a PR but would first like to know whether this contribution is welcome. Also I'm of course open to suggestions on category name and gems that should belong there.

Those are all gems that in one way or another provide some way of telling whether a web application (rails or not) is fully functioning.

Some examples of gems that would belongs to that category:

- https://www.ruby-toolbox.com/projects/health_bit
- https://www.ruby-toolbox.com/projects/status_cat
- https://www.ruby-toolbox.com/projects/health_check
- https://www.ruby-toolbox.com/projects/okcomputer

**Comment by colszowka** [comment]
@andrepiske Of course that's welcome as an addition, please feel free to submit a corresponding PR to https://github.com/rubytoolbox/catalog :+1:
