### ISSUE TITLE
Bring back category bar graphs?

### ISSUE THREAD

**Issue by indirect** [rubytoolbox/rubytoolbox#126]
The new toolbox is amazing! I'm super excited to see it launch. Are there plans to bring back the bar graphs that used to be at the top of each category? I loved being able to see at a glance if there were 2x or 10x differences between projects, and I find it much harder to do the mental math to compare overall scores while scrolling through the list of projects.

Thanks again for your work relaunching this great resource!

**Comment by colszowka** [comment]
Yes! This is definitely something that was helpful and I want to add it back. Thanks for bringing it up :) Another thing I was thinking about is some kind of toggle to switch into a more concise table-based view, which would make it much easier to compare project metrics. But regardless, yes, the graphs should come back.

**Comment by colszowka** [comment]
Good news, this is now finally live via #401 - didn't even take a full year... :blush: Thanks for the patience :)

In other news the side-by-side table comparison view I mentioned in my previous comment here is coming soon via #398 as well.
