### ISSUE TITLE
Clean up / Split API clients category

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#131]
The [API clients category](https://www.ruby-toolbox.com/categories/api_clients) is currently a bit of a dump for all kinds of at the core unrelated gems, it should probably be split up into dedicated categories per service, i.e. have a full category group "API clients", and underneath that "github clients", "twitter clients", "facebook clients", "Amazon Web Services clients" etc.

Not sure where to draw the line which sites should have their own category however. It surely does not make sense to have a category with 1 existing ruby client for each service / product on the internet... We could only put services large enough to have multiple maintained and fitting libraries as their own categories?

**Comment by franklinyu** [comment]
How would the file structures be? Do you want it to stay in the same YAML file, or would you like a separate file for every sub-category?

**Comment by colszowka** [comment]
@franklinyu It needs to be a separate file per new API category as that's the only allowed way in the [catalog structure](https://github.com/rubytoolbox/catalog#structure)

**Comment by franklinyu** [comment]
Ok good. Currently it’s

```plain
catalog/
  Web_Apps_Services_Interaction/
    _meta.yml
    api_clients.yml
```

I think it would be

```plain
catalog/
  Web_Apps_Services_Interaction/
    _meta.yml
    API_Clients/
      _meta.yml
      MediaWiki_Clients.yml
      Google_Clients.yml
      ...
      Other_Clients.yml
```

Right?

**Comment by colszowka** [comment]
@franklinyu 

Only one level of nesting is possible, so rather:

```
catalog/
    API_Clients/
      _meta.yml
      MediaWiki_Clients.yml
      Google_Clients.yml
      ...
      Other_Clients.yml
```

Thanks!

**Comment by franklinyu** [comment]
So you would like to “promote” the API Client to a first-class category?

**Comment by colszowka** [comment]
I think it's the best option we have, yeah. Maybe let's on the way also name it "HTTP API Clients", to make it clear we're talking about web based stuff here :)
