### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by WaKeMaTTa** [rubytoolbox/rubytoolbox#135]
Hello,

When rubytoolbox was dead I started using https://ruby.libhunt.com

Maybe it will inspire you @colszowka

**Comment by colszowka** [comment]
Hey, thanks! 

This was also brought up and discussed in the general future discussion issue #1.

In general I think this is too broad of an issue to tackle, if you have concrete feature suggestions please create a dedicated issue for that. Thank you!
