### ISSUE TITLE
New Category: Service Objects

### ISSUE THREAD

**Issue by konung** [rubytoolbox/rubytoolbox#137]
There are several Service Objects gems out there, that should probably be grouped into a category

- https://github.com/collectiveidea/interactor
- https://github.com/jspillers/simple_service
- https://github.com/trailblazer/trailblazer-operation
- https://github.com/hashrocket/decent_exposure
- https://github.com/cypriss/mutations
- https://github.com/saturnflyer/surrounded

**Comment by colszowka** [comment]
@konung Sounds good to me, could you submit a PR to the catalog? Maybe together with #136 would deserve their own category group, too, since I can't think of anything other than "Developer Tools" to fit, and that is already kind of a catch-all bucket... Maybe something like "Code organization" or such would make sense?

**Comment by konung** [comment]
Sure thing Christoph.

I was thinking:

Code_Organization
 - frameworks.yml
 - service_objects.yml
 - view_objects.yml

Etc.

I’ll set it up and PR.

Have a great day!

Nick Gorbikoff
nick.gorbikoff@gmail.com

**Comment by colszowka** [comment]
Perfect, thank you!

**Comment by colszowka** [comment]
One minor note - For the display names and permalinks of the categories, make sure they work "standalone" without the accompanying group name. For service objects this probably works on it's own, frameworks maybe should rather be "Code organization(architecture?) frameworks"?

**Comment by pmackay** [comment]
Could this be closed now, given https://www.ruby-toolbox.com/categories/Service_Objects ?

**Comment by konung** [comment]
My bad . I thought it would be closed auto-magically™ once the code was merged.  Thank you
