### ISSUE TITLE
Search from the site returns entries not in the catalog.

### ISSUE THREAD

**Issue by cedlemo** [rubytoolbox/rubytoolbox#145]
When I do a search from the site https://www.ruby-toolbox.com/, it returns me results that are not referenced in the catalog. Did I misunderstand something ?

**Comment by colszowka** [comment]
The toolbox indexes all Rubygems, not only those categorized - this is an important feature since it allows you to find stuff even if it's not categorised :)

**Comment by cedlemo** [comment]
ha ok, I did misunderstand, my bad. ;)
