### ISSUE TITLE
Add DuckRails?

### ISSUE THREAD

**Issue by iridakos** [rubytoolbox/rubytoolbox#148]
I believe [DuckRails](https://github.com/iridakos/duckrails) belongs here but I am not sure in which category it should be added... I would add it to one of the following (ordered based on my take on its relevance to the category):

* Developer Tools > Productivity _*_
* Testing > Mocking
* Web Apps, Services & Interaction > Productivity _*_

_*  new sub category_

**Comment by BookOfGreg** [comment]
@iridakos You may be looking for https://github.com/rubytoolbox/catalog if you wish it to be listed on the site.

**Comment by iridakos** [comment]
@BookOfGreg Hi and thanks.

I opened this issue following this direction:
> if your changes could need discussion, please create an issue on the main repo up-front for further discussion.

**Comment by harisgeo** [comment]
+1 for **Developer Tools > Productivity**

**Comment by colszowka** [comment]
Hmm, "Productivity" seems a bit broad - after all, basically every single rubygem could raise your productivity in some way :) 

I would suggest "Web apps (...) > Mock API Servers"

**Comment by iridakos** [comment]
@colszowka Thanks, I agree with you. 

I proceeded with your suggestion here: [https://github.com/rubytoolbox/catalog/pull/77](https://github.com/rubytoolbox/catalog/pull/77)

**Comment by colszowka** [comment]
Cool, thanks!

**Comment by iridakos** [comment]
**Question:** the [project page](https://www.ruby-toolbox.com/projects/iridakos/duckrails) looks empty, I suppose the job that will retrieve the info from GitHub hasn't run yet, correct?

**Comment by iridakos** [comment]
@colszowka Hi, any updates on this? The [project page](https://www.ruby-toolbox.com/projects/iridakos/duckrails) still looks as if it hasn't been synchronized with the repo's data. Thanks.
