### ISSUE TITLE
[UI] Project box styling

### ISSUE THREAD

**Issue by GBH** [rubytoolbox/rubytoolbox#168]
Gotta say that I don't like how it looks. Black text bits scattered over empty white space like bird seeds on the snow. Hard for the eye to land on anything specific.  

Feel like it should be way more compact. Stats are just 8 data-points and they take up more than 50% of the box when description is just a single sentence. 

What do you guys think? I can't be the only one.

Willing to take a stab at too.

**Comment by colszowka** [comment]
Thanks for your honest feedback @GBH  :)

I agree that quite a bit of space is wasted, however I would prefer not to cram things together too much.

Maybe, if you'd like to suggest improvements, maybe as a starting point you could check out the repo locally and play around with the [variables bulma, the CSS framework we use](https://bulma.io/documentation/overview/variables/) regarding spacing?

Bear in mind however that it should also work for responsive / mobile view:

![bildschirmfoto vom 2018-03-22 22 46 26](https://user-images.githubusercontent.com/13972/37800472-2aa40b86-2e23-11e8-8342-0596ec37f384.png)

**Comment by colszowka** [comment]
Idle timeout, closing this one. Feel free to reopen based on previous comment from me, thank you!
