### ISSUE TITLE
Bring back old site

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#2]
As became evident from the discussion in #1 it might take some time until we have a new version of the site going, so we should bring the existing one back online in the meantime.

@thejonanshow offered Heroku's help on this.

**Comment by franklinyu** [comment]
Even a read-only version would suffice. New users can be directed (by a banner, for example) to the new under-construction site.

**Comment by t0nylombardi** [comment]
Is there any Downside to DigitalOcean versus Heroku?  I feel like you can get more tweakability and scalability at a cheaper rate.

**Comment by franklinyu** [comment]
@t0nylombardi I think Heroku is offering a free hosting for this project, so not “at a cheaper rate”.

**Comment by pmichna** [comment]
@colszowka Are asking for any specific help or are you just informing that this issue is in progress?

**Comment by obfuscoder** [comment]
What are the requirements for a hosting platform? How much monthly/daily traffic is expected? How many requests per day/second in average and at peaks are to be expected? What database backend is required?

**Comment by bradland** [comment]
Please take a moment to understand what has already come to pass before commenting. Heroku has offered their platform as a form of sponsorship, and there is no question that they can scale to the needs of the RubyToolbox site.

You can see Jonan's original comment here https://github.com/rubytoolbox/rubytoolbox/issues/1#issuecomment-309642631

@colszowka What is needed to get the old site up? Is it possible to get the old source code committed to this repository, along with a database dump? I get the sense that there are people willing to assist, but without the code & data, everything is at a standstill two months after the original issue was posted.

**Comment by t0nylombardi** [comment]
I agree with @bradland.  Post the old code and we can take chunks of the old code, rewrite it and put it in a new Rails5 shell.  

- Like what @bradland said we can keep the same data.
- We can at least start coding the models. 
- Start working on the services that pulled the info.  
- The rest of the incompatibilities we can work on after.

**Comment by sandstrom** [comment]
Exciting to see the Ruby Toolbox being brought back to life 😄 

Might not be the right place to ask, but are you planning to do server-side rendered views, or Rails API-style with a front-end library (for example Ember)?

**Comment by colszowka** [comment]
Closing this in favor of https://www.ruby-toolbox.com/blog/2018-02-01/lets-push-things-forward

**Comment by colszowka** [comment]
@sandstrom It's just a plain old Rails site :)
