### ISSUE TITLE
Relevant project data and scoring

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#4]
Here's what the current site was showing for a project:

![toolbox-project](https://user-images.githubusercontent.com/13972/27772920-7544b86a-5f6c-11e7-9cf4-dd494446a594.png)

Most of this can be taken from rubygems/github APIs. Where gems did not provide this data (say for rdoc), the site fell back on common tools like rubydoc.info

"Special case" project data:
* Development activity - this was ranking the average date of the last 20 or 30 commits on the repo. If these are far behind, it's a fairly good indicator the project is inactive
* Reverse dependencies / depending gems count - This did not exist on rubygems back in the day, but (I think because it's needed by bundler) is nowadays part of the rubygems API. Widespread usage of a library for a lot of other projects is a pretty good indicator of popularity
* The first commit date is not available on the github API, you have to traverse the default branch way back to find it. Luckily, this only has to be done once :) Alongside the first release date, this shows project age and and, again, imho is a good indicator of health and stability (granted, if the project is old and still kicking ;)

I think https://ossert.evilmartians.io/rake can also be an excellent source of inspiration for project data.

Regarding scoring:

The scores themselves on the toolbox have always been derived only from the watchers/forks on the repo and rubygem downloads. It might be worthwile to either include project health in the score, but going a similar path as with the "special fields" mentioned above and/or making clear "grades" like OSSERT and simply giving you the info to give you an overview to make your own decision can be totally sufficient.

**Comment by colszowka** [comment]
This should also be linked on #1 ;)

**Comment by andrew** [comment]
cc @benjam as this is also something he's working on for Libraries.io with the people behind ossert on getting together a list of good classification measures: https://github.com/librariesio/libraries.io/issues/1486

**Comment by colszowka** [comment]
Here's a quick written overview of the data we've been showing so far, including notes if there was some special fallback logic involved:

Urls:

- Website (from rubygem or github repo)
- RDoc (from rubygem or fallback to rubydoc.info)
- Wiki (from rubygem)
- Source Code (from rubygem)
- Bug Tracker (from rubygem or fallback to github issues if enabled)
- Mailing List (from rubygem)

Rubygem:

- Total Gem Downloads
- Number of releases
- Current Version
- First release date
- Latest release date
- Number of depending gems
- List of dependencies
- List of most popular depending gems

Github Repo:

- Watchers
- Forks
- Development activity (average date of last 30 commits)
- Last commit date
- First commit date
- Number of issues (if applicable)
- Number of contributors
- Top contributor names

**Comment by hmistry** [comment]
I had some thoughts as I [commented](https://github.com/rubytoolbox/rubytoolbox/issues/7#issuecomment-334061749) on #6.

Other than development activity, maybe it's worth tracking issues and pr activity. If you consider a useful gem that is feature frozen and bug free and hasn't needed any updates, you could still have activity in issues. I'm not sure about PR activity usefulness - need to think about it more.

I think we should breakdown total gem downloads by month (or some time period) to gain some depth about the activity. For example: there are 2 gems, both with 10M downloads. First one has been ramping up over the last 5 years and the second one ramped up first 2 years, hit its peak in year 3, and has been declining in last 2 years. A monthly downloads chart of this would convey the second gem is on the decline and warrants an investigation if it's still worth using.

**Comment by colszowka** [comment]
This is outdated / stale, closing
