### ISSUE TITLE
Project detail view should show the category

### ISSUE THREAD

**Issue by unikitty37** [rubytoolbox/rubytoolbox#414]
When viewing an individual project, the page does not indicate what category or categories the project is in.

Use case:

- I want to find an alternative to `typogruby` that is still getting updated.
- I look at the categories list, but can't find a relevant category.
- I enter `typogruby` into the search box, and click on the result.
- From here, I should be able to click on the category and see what else is in that category. But I can't, and I still have no idea what category I should be looking under.

Would it be possible to display category links on the project detail view?

**Comment by FranklinYu** [comment]
[`typogruby`](https://www.ruby-toolbox.com/projects/typogruby) is *not* categorized. Categorized projects do show category in detail view, such as [`multi_json`](https://www.ruby-toolbox.com/projects/multi_json).

**Comment by unikitty37** [comment]
Ah — no wonder I couldn't find a category for it! I thought everything *was* in a category, which is why I never checked other projects 😊 

Sorry for the issue spam.
