### ISSUE TITLE
Maintained forks?

### ISSUE THREAD

**Issue by vfonic** [rubytoolbox/rubytoolbox#488]
There's one issue that would be great to have addressed:
Sometimes there's a gem who's maintainer just disappeared, but there's an active little community (or one person) interested in maintaining the gem. Think of cancan => cancancan. It took me about a year until I discovered that there's cancancan gem forked and maintained.
If rubytoolbox would show active forks of the gem, that would be such a great feature!

**Comment by FranklinYu** [comment]
Shall we automatically detect that, or record the linkage in catalog?

**Comment by vfonic** [comment]
We could leverage existing rubytoolbox tools to see what comes up from these forks and if that's a good way to go about it or should the linkage be in catalog.

**Comment by BookOfGreg** [comment]
I believe there was recently a feature to try clean up all the devise forks that were skewing a metric.
Would https://github.com/rubytoolbox/rubytoolbox/pull/377 be useful information for this thread?

**Comment by vfonic** [comment]
I believe so, definitely! That PR addressed the issue of "bugfix forks",
and those are the ones we'd like to exclude from the list of "maintained
forks", right?

Thanks for pointing that out!

**Comment by colszowka** [comment]
Hey all, I'm currently going through a bunch of older issues and I would suggest to merge this with the newer issue at https://github.com/rubytoolbox/rubytoolbox/issues/611 where I wrote up a proposal how we could address this. Please take a look!
