### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#5]
Very closely related to #4, essentially, we could take the data either from the source, a.k.a. github and rubygems APIs, or from libraries.io. Since the latter is the more generic and re-usable data source, I would really like to go with that (as indicated in #1), but we'll need to figure out what might be missing. Most 
notably, currently libraries.io [does not offer rubygem download counts](https://github.com/rubytoolbox/rubytoolbox/issues/1#issuecomment-309235799). They do have recently released [open data access](https://github.com/rubytoolbox/rubytoolbox/issues/1#issuecomment-308729759) but I'm not sure the release frequency is sufficiently high (the toolbox used to update the stats on categorized projects on each gem release and also daily, no matter what)

**Comment by andrew** [comment]
@colszowka we have the rest API: https://libraries.io/api and a firehose event feed of all new versions: http://librariesio.github.io/firehose-stream

The open data release could be used as the initial backfill for all rubygems and github/gitlab/bitbucket repositories they reference. 

Download counts for rubygems shouldn't take too long to add and start downloading, we do have the number of open source repositories that list each rubygem as a dependency, similar to google page rank, which gives very good usage stats that aren't affected by CI or other bots downloading gems over and over.

We also can potentially set up a new API or way of exporting more data on mass as that's not something anyone has requested before, happy to chat through what would work best for you and also our plans for the future too.

**Comment by tkz79** [comment]
Just to throw the idea in the ring.... Youtube. It would be more for the newer people, but I used to love having a video tutorial up on a side monitor while I read the documentation. 

Very easy API to work with... just requires a video id to get all the data for it. 

It is however subject to moderation and spam.... but i think 98% of it can be automated.

**Comment by colszowka** [comment]
So, I finally took the time to have a closer look at the data the libraries.io API currently provides, based on [the list of values that were visible on each project on the Ruby Toolbox so far](https://github.com/rubytoolbox/rubytoolbox/issues/4#issuecomment-322853735) 

Urls:

* [x] Website (from rubygem or github repo)
* [ ] RDoc (from rubygem or fallback to rubydoc.info)
* [ ] Wiki (from rubygem)
* [ ] Source Code (from rubygem)
* [ ] Bug Tracker (from rubygem or fallback to github issues if enabled)
* [ ] Mailing List (from rubygem)

Rubygem:

* [ ] Total Gem Downloads
* [x] Number of releases
* [x] Current Version
* [x] First release date
* [x] Latest release date
* [ ] List of dependencies
* [ ] Number of depending gems
* [ ] List of most popular depending gems

I understand that the dependencies should be part of https://libraries.io/api/rubygems/rails/latest/dependencies, but for rails, I only get `"depencencies": []`. Also, in the example response for dependencies of `npm/grunt` in the API docs, the keys "dependents_count" and 
"dependent_repos_count" exist, but I don't get these for rails.

The dependents API (https://libraries.io/api/rubygems/rails/dependents) lists all dependents, but with full info and paginated. We can fetch the total number from the "Total" header. The API as a bit on the slow side, a single call for rails took ~6seconds for me.

Personally, I would say the actual list of dependencies and dependents is somewhat secondary, but the total number of dependents is pretty interesting, I would like to keep that.

Github Repo:

* [x] Watchers
* [x] Forks
* [ ] Development activity (average date of last 30 commits)
* [x] Last commit date
* [ ] First commit date
* [ ] Number of issues (if applicable)
* [ ] Number of contributors
* [ ] Top contributor names

---

With that being said, here is a list of values I think are important for Toolbox project overviews, but are missing from libraries.io (on the API, from what I have seen, at least) - @andrew could you maybe comment on whether those could be added to / provided by the libraries.io API?

* [ ] RDoc (from rubygem or fallback to rubydoc.info)
* [ ] Wiki (from rubygem)
* [ ] Source Code (from rubygem)
* [ ] Bug Tracker (from rubygem or fallback to github issues if enabled)
* [ ] Mailing List (from rubygem)
* [ ] Total Gem Downloads
* [ ] Number of depending gems
* [ ] Development activity (average date of last 30 commits)
* [ ] First commit date
* [ ] Number of issues (if applicable)
* [ ] Number of contributors
* [ ] Number of collaborators (*this one would be new)

How often does Libraries.io update project data in general?

**Comment by colszowka** [comment]
Short update, I had another look at the data available on the web UI for rails at https://libraries.io/rubygems/rails

There is a documentation link, but it seems to do the immediate fallback to rubydoc.info and ignores the link embedded in the gem (See https://rubygems.org/gems/rails)

I also noticed the number of contributors is visible in the sidebar, so that number must be somewhere in that database already :)

**Comment by sclinede** [comment]
@colszowka actually looks like I have all the data u need in Ossert DB :) take a look for numbers on gems pages and if u'll find them OK I could provide you my dump any day. Also we could create an API for that data, if u want

**Comment by sclinede** [comment]
Of course for almost all metrics I have not only the count but the values itself (e.g. dependencies, contributors and so on)

**Comment by sclinede** [comment]
And last. Updates in Ossert are not very frequent, it's about once in couple months. I thought it's enough for my case

**Comment by colszowka** [comment]
It's been a while... Closing this since as mentioned above it seemed to make most sense to source the data directly to ensure it's always (reasonably) up to date, no additional point of failure is introduced and have all the data required available (there's for example some specific queries in the graphql github call to get latest commit dates etc.) - thanks for your input everyone
