### ISSUE TITLE
Displayed project data and scores are incorrect

### ISSUE THREAD

**Issue by pboling** [rubytoolbox/rubytoolbox#60]
The # of downloads is correct as on RubyGems.org, but the data from Github is all sorts of wrong, resulting in scores that are also wrong.
<img width="1007" alt="has-bit-field-github" src="https://user-images.githubusercontent.com/19505/34587076-970f1a7c-f15b-11e7-88fd-1722db9a6846.png">
<img width="808" alt="has-bit-field-ruby-toolbox" src="https://user-images.githubusercontent.com/19505/34587077-97263518-f15b-11e7-9f26-381b53a21597.png">

**Comment by colszowka** [comment]
Hey Peter, it's still early stages and beta. The numbers are all random, except Rubygems downloads, which I added this week. Please have a look at the pr history if you're interested!

GitHub data is inbound, pending PR #59, which I need to test a bit. Calculating scores is prepared, but please bear with me as I get everything ready :)
