### ISSUE TITLE
View jumps to readme on hovering over sponser logo

### ISSUE THREAD

**Issue by sonalkr132** [rubytoolbox/rubytoolbox#757]
Browser: Google Chrome Version 84.0.4147.105

![ezgif-6-087b93191365](https://user-images.githubusercontent.com/7680662/95290155-31dce000-088a-11eb-9ef7-5b87ecebe18c.gif)

**Comment by colszowka** [comment]
Oh great, why would it do that !? Will check it out, thank you for the report!

**Comment by colszowka** [comment]
Well it does not happen on Firefox so please just use firefox :) I'm quite mystified by this issue

**Comment by colszowka** [comment]
Yay managed to fix it :) https://github.com/rubytoolbox/rubytoolbox/pull/802
