### ISSUE TITLE
NLP, Data Science and Machine Learning

### ISSUE THREAD

**Issue by arbox** [rubytoolbox/rubytoolbox#8]
Hi @colszowka ,

a couple of years ago we discussed new categories for the RubyToolbox, but since then we didn't manage to incorporate libraries from the NLP, Data Science and Machine Learning areas into the Toolbox. Now it's possible and I'll try to add to the Catalog all sources from my lists:

- [Ruby NLP](https://github.com/arbox/nlp-with-ruby)
- [Ruby Machine Learning](https://github.com/arbox/machine-learning-with-ruby)
- [Ruby Data Science](https://github.com/arbox/data-science-with-ruby)

As you asked for discussion I post here some concerns:
- through the addition of all the topics from these lists the Toolbox gets a lot of new categories like so the question is how coarse/fine the classification should be
- the categorization should be hierarchical and multiple since many ML projects are related to the Data Science and NLP too and may have a general category like `ml` as well as a specific category like `svm` .

Are there any guidelines for the categorizations? Are multiple categories welcome for now?

**Comment by colszowka** [comment]
@arbox Sounds great! I would really like to (at least for now) keep the simple category structure as it was on the old site, but I think this would work:

Group: Natural Language Processing
Categories:
- Optical Character Recognition
- Numbers, Dates, and Time Parsing (I think a similar category exists, it probably should be moved)
- Machine Translation
- Sentiment Analysis

Maybe the "NLP Pipeline Subtasks" from your list would justify their own top level category group as they would be the lower-level building blocks for the higher-level libraries in the general NLP category?

Does this make sense to you?

Regarding the influx of lots of categories: I wouldn't worry about that, the more structured information we have the better. At the end this is simply UX challenge, enabling users to find what they are looking for quickly. Should be solvable on the UI side (famous last words ;)

**Comment by arbox** [comment]
@colszowka 
Thank you for you patience, it took me another year to start with this topic.

Please look at the first attempt: rubytoolbox/catalog#202.

I would like to make this first small addition to learn the mechanics and then export most of the lists to Ruby Toolbox.

**Comment by colszowka** [comment]
@arbox Ha, no worries! Life tends to keep us busy, but it's a good thing :ferris_wheel:

**Comment by arbox** [comment]
@colszowka 
We may want to close this issue and move work to the Catalog :)

**Comment by colszowka** [comment]
@arbox Agreed!
