### ISSUE TITLE
Make each metric linked to an explanation page

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#90]
It might be nice to have a detailed explanation of each metric, and what it might mean for judging a project.

This could become a part of the help as per #88

In addition to the explanation, some distribution graphs for that metric as per #89 might also be cool.

**Comment by itsderek23** [comment]
I agree. 

The one that stands most to me is the metric next to the beaker:

![image](https://user-images.githubusercontent.com/7880/35997721-94d77abe-0cd7-11e8-8d65-c4e063628f3d.png)

I haven't looked at the code yet to see how this is generated. For a small step forward, I can review the code and add an HTML title attribute or a tooltip to the metric.

**Comment by colszowka** [comment]
For that particular one there is even a dedicated issue already, #80 - let's move the discussion around that over there :)

**Comment by itsderek23** [comment]
Ha - thx. I'll check that out.

**Comment by colszowka** [comment]
For the majority of metrics this was actually built and added a while ago as per https://www.ruby-toolbox.com/blog/2019-01-24/metrics-documentation-and-statistics

However, for scores apparently we still don't have it, we should use https://github.com/rubytoolbox/rubytoolbox/issues/80 for that one however, so gonna close this here
