### ISSUE TITLE
Search seems to be broken?

### ISSUE THREAD

**Issue by nadrooJ** [rubytoolbox/rubytoolbox#979]
https://www.ruby-toolbox.com/search?q=rails

![image](https://user-images.githubusercontent.com/13659818/159960494-c1a14928-81f4-43a7-b5a1-243ff0c3402c.png)

**Comment by colszowka** [comment]
@nadrooJ thanks for reporting, I also got an alert about this from monitoring and fixed it yesterday, there was an issue with the search index server. It should be working fine again now
